"""
Agent training and regression cases for 小觅.

This module intentionally keeps the cases deterministic and importable:
- normal_agent: demand discovery + card recommendation flow.
- map_agent: spatial planning + map annotation flow.

Run directly to export the 5000 generated cases as JSON:
    python backend/app/services/agent_training_cases.py
"""
from __future__ import annotations

import json
from copy import deepcopy
from typing import Any


PHRASING_VARIANTS = [
    ("direct", "{user}"),
    ("casual", "小觅，{user}"),
    ("constraint_first", "先按我的限制来：{user}"),
    ("uncertain", "我有点拿不准，{user}"),
    ("followup", "接着上一轮继续，{user}"),
    ("urgent", "现在就要决定，{user}"),
    ("polite", "麻烦帮我看看：{user}"),
    ("short", "{user}，别推荐太多"),
    ("negative_context", "上次推荐不太准，这次{user}"),
    ("action_oriented", "{user}，可以直接给我下一步操作"),
]


NORMAL_SCENARIO_VARIANTS = [
    {
        "name": "base",
        "template": "{text}",
        "known_preferences": [],
        "must_infer": [],
        "must_include": [],
    },
    {
        "name": "budget_sensitive",
        "template": "{text}，预算希望控制住，别默认推贵的",
        "known_preferences": ["price_sensitive"],
        "must_infer": ["价格敏感"],
        "must_include": ["预算解释"],
    },
    {
        "name": "distance_sensitive",
        "template": "{text}，最好近一点，路上别折腾",
        "known_preferences": ["distance_sensitive"],
        "must_infer": ["距离敏感"],
        "must_include": ["距离/交通理由"],
    },
    {
        "name": "social_context",
        "template": "{text}，我可能和朋友一起，环境别太尴尬",
        "known_preferences": [],
        "must_infer": ["社交场景"],
        "must_include": ["适合聊天/同行人的理由"],
    },
    {
        "name": "after_plan",
        "template": "{text}，吃完可能还要去地铁或找地方坐会儿",
        "known_preferences": [],
        "must_infer": ["后续安排"],
        "must_include": ["心愿单/地图承接"],
    },
]


PRODUCT_SCENARIO_VARIANTS = [
    {
        "name": "base",
        "template": "{text}",
        "must_infer": [],
        "must_include": [],
    },
    {
        "name": "only_feature",
        "template": "我只是问功能，不要给餐厅卡：{text}",
        "must_infer": ["产品功能咨询"],
        "must_include": ["不推荐餐厅"],
    },
    {
        "name": "entry_confusion",
        "template": "{text}，入口在哪、点了以后下一步是什么",
        "must_infer": ["入口/操作闭环"],
        "must_include": ["说明入口和下一步"],
    },
    {
        "name": "compare_with_recommendation",
        "template": "{text}，它和直接推荐餐厅有什么区别",
        "must_infer": ["产品概念对比"],
        "must_include": ["说明和餐厅推荐的关系"],
    },
    {
        "name": "broken_flow",
        "template": "{text}，如果点了没反应该怎么办",
        "must_infer": ["异常处理"],
        "must_include": ["排查或反馈方式"],
    },
]


MAP_SCENARIO_VARIANTS = [
    {
        "name": "base",
        "template": "{text}",
        "known_preferences": [],
        "must_infer": [],
        "must_include": [],
        "map_actions": [],
    },
    {
        "name": "budget_route",
        "template": "{text}，也帮我看一下预算别超太多",
        "known_preferences": ["price_sensitive"],
        "must_infer": ["预算约束"],
        "must_include": ["价格和路线综合"],
        "map_actions": ["rank_by_price_route_balance"],
    },
    {
        "name": "transit_priority",
        "template": "{text}，优先考虑地铁或回去方便",
        "known_preferences": ["distance_sensitive"],
        "must_infer": ["交通便利"],
        "must_include": ["地铁/返程理由"],
        "map_actions": ["mark_transit_nodes"],
    },
    {
        "name": "time_pressure",
        "template": "{text}，我时间有点紧，别安排太绕",
        "known_preferences": [],
        "must_infer": ["时间压力", "少绕路"],
        "must_include": ["时间风险"],
        "map_actions": ["rank_by_time_cost"],
    },
    {
        "name": "wishlist_memory",
        "template": "{text}，如果心愿单里有合适的也一起参考",
        "known_preferences": [],
        "must_infer": ["心愿单参考"],
        "must_include": ["说明是否使用心愿单"],
        "map_actions": ["compare_with_wishlist"],
    },
]


NORMAL_AGENT_SEEDS: list[dict[str, Any]] = [
    {
        "category": "budget_light_nearby",
        "history": ["我不吃辣，以后别推重庆秀山小面"],
        "user": "预算30以内，近一点，想吃清淡或轻食",
        "context": {"known_preferences": ["avoid_spicy", "avoid_restaurant:重庆秀山小面"], "location": "上海全市"},
        "expected": {
            "intent": "recommend_restaurants",
            "must_infer": ["不辣", "预算<=30", "距离敏感", "轻食/清淡"],
            "must_ask_if_missing": ["是否现在就吃", "是否吃完有后续安排"],
            "must_include": ["2-3张餐厅卡片", "为什么符合不辣和预算", "加入心愿单/加入地图动作"],
            "must_avoid": ["重庆秀山小面", "川菜/湘菜/火锅等重辣优先"],
            "ui_actions": ["render_cards", "offer_wishlist", "offer_add_to_map"],
        },
    },
    {
        "category": "sweet_craving",
        "history": [],
        "user": "我想吃甜的",
        "context": {"known_preferences": [], "location": "上海全市"},
        "expected": {
            "intent": "sweet_craving",
            "expected_intents": ["sweet_craving"],
            "must_infer": ["甜口", "不是正餐主菜", "需要甜品/饮品/下午茶方向"],
            "must_ask_if_missing": ["甜品/奶茶/蛋糕/糖水/下午茶偏好", "是否要能坐"],
            "must_include": ["先不推正餐", "甜品/奶茶/咖啡甜点候选", "加入心愿单/加入地图动作"],
            "must_avoid": ["东北菜", "川菜", "火锅", "烧烤", "盖饭", "海鲜", "日料", "烧肉"],
            "expected_candidate_tags": ["甜品", "奶茶", "咖啡", "蛋糕", "糖水", "下午茶"],
            "forbidden_candidate_tags": ["东北菜", "川菜", "火锅", "烧烤", "盖饭", "面馆", "海鲜", "日料", "刺身", "烧肉"],
            "expected_dialogue_move": "ask_clarifying_or_recommend_sweet_options",
            "ui_actions": ["render_cards", "offer_wishlist", "offer_add_to_map"],
        },
    },
    {
        "category": "sweet_nearby_seating",
        "history": [],
        "user": "想吃甜品，附近能坐一会儿",
        "context": {"known_preferences": [], "location": "静安区"},
        "expected": {
            "intent": "sweet_craving",
            "expected_intents": ["sweet_craving", "nearby_search", "seating_needed"],
            "must_infer": ["甜品", "附近", "可坐", "休息/聊天"],
            "must_ask_if_missing": ["预算或是否要安静"],
            "must_include": ["甜品/咖啡甜点", "座位友好", "距离理由"],
            "must_avoid": ["正餐主菜首推", "只适合外带的小窗口", "海鲜/日料靠下午茶标签误入"],
            "expected_candidate_tags": ["甜品", "咖啡", "蛋糕", "糖水", "下午茶"],
            "forbidden_candidate_tags": ["东北菜", "川菜", "火锅", "烧烤", "盖饭", "海鲜", "日料", "刺身", "烧肉"],
            "ui_actions": ["render_cards", "show_seating_tags"],
        },
    },
    {
        "category": "milk_tea_less_sugar",
        "history": [],
        "user": "想喝奶茶，但别太甜",
        "context": {"known_preferences": ["low_sugar"], "location": "徐汇区"},
        "expected": {
            "intent": "sweet_craving",
            "expected_intents": ["sweet_craving", "less_sugar"],
            "must_infer": ["奶茶", "少糖", "饮品而非正餐"],
            "must_ask_if_missing": ["是否要无糖/三分糖", "是否要可坐"],
            "must_include": ["奶茶/饮品", "少糖建议", "避开高糖甜品"],
            "must_avoid": ["东北菜", "重辣正餐", "默认全糖", "海鲜/日料正餐"],
            "expected_candidate_tags": ["奶茶", "饮品", "咖啡", "下午茶"],
            "forbidden_candidate_tags": ["东北菜", "川菜", "火锅", "烧烤", "盖饭", "海鲜", "日料", "刺身", "烧肉"],
            "ui_actions": ["render_cards", "show_sugar_notes"],
        },
    },
    {
        "category": "sweet_after_meal_budget",
        "history": [],
        "user": "饭后想来点甜的，预算30",
        "context": {"known_preferences": ["price_sensitive"], "location": "黄浦区"},
        "expected": {
            "intent": "sweet_craving",
            "expected_intents": ["sweet_craving", "budget_filter"],
            "must_infer": ["饭后甜点", "预算<=30", "轻量甜口"],
            "must_ask_if_missing": ["想带走还是坐一会儿"],
            "must_include": ["30元内甜品/奶茶/糖水", "饭后轻量理由"],
            "must_avoid": ["正餐套餐首推", "超过预算不说明", "海鲜/日料正餐"],
            "expected_candidate_tags": ["甜品", "奶茶", "糖水", "蛋糕", "饮品"],
            "forbidden_candidate_tags": ["东北菜", "川菜", "火锅", "烧烤", "盖饭", "海鲜", "日料", "刺身", "烧肉"],
            "ui_actions": ["render_cards", "show_budget_tags"],
        },
    },
    {
        "category": "cool_craving_plain",
        "history": [],
        "user": "我想吃凉的",
        "context": {"known_preferences": [], "location": "上海全市"},
        "expected": {
            "intent": "cool_craving",
            "expected_intents": ["cool_craving"],
            "must_infer": ["凉的", "冷食/冰饮/清爽", "不是热炒热汤"],
            "must_ask_if_missing": ["想正餐凉面/沙拉，还是冷饮冰品"],
            "must_include": ["明确避开热汤热炒", "冷饮/冰品/凉面/清爽轻食方向"],
            "must_avoid": ["炒菜", "热汤", "火锅", "冒菜", "烧烤"],
            "expected_candidate_tags": ["凉面", "冷食", "冰品", "饮品", "奶茶", "糖水", "沙拉", "轻食", "清爽"],
            "forbidden_candidate_tags": ["热汤", "火锅", "冒菜", "炒菜", "烧烤", "麻辣"],
            "ui_actions": ["render_cards", "ask_subtype_if_needed"],
        },
    },
    {
        "category": "cool_not_hot_meal",
        "history": [],
        "user": "不想吃热的，来点清爽降温的",
        "context": {"known_preferences": [], "location": "上海全市"},
        "expected": {
            "intent": "cool_craving",
            "expected_intents": ["cool_craving"],
            "must_infer": ["不热", "清爽", "降温"],
            "must_ask_if_missing": ["是否要吃饱还是喝点冰的"],
            "must_include": ["清爽冷食/冰饮", "避免热菜"],
            "must_avoid": ["热汤", "热炒", "火锅", "砂锅"],
            "expected_candidate_tags": ["凉面", "冷食", "冰品", "饮品", "奶茶", "糖水", "沙拉", "轻食", "清爽"],
            "forbidden_candidate_tags": ["热汤", "火锅", "冒菜", "炒菜", "烧烤", "麻辣"],
            "ui_actions": ["render_cards", "show_cool_reason"],
        },
    },
    {
        "category": "cool_food_not_only_drink",
        "history": [],
        "user": "想吃冰一点的，但最好能当一餐",
        "context": {"known_preferences": [], "location": "上海全市"},
        "expected": {
            "intent": "cool_craving",
            "expected_intents": ["cool_craving"],
            "must_infer": ["冰一点", "能当一餐", "冷食优先"],
            "must_ask_if_missing": ["能否接受凉面/沙拉/轻食"],
            "must_include": ["凉面/沙拉/轻食优先", "饮品作为备选"],
            "must_avoid": ["只推奶茶", "热炒热汤"],
            "expected_candidate_tags": ["凉面", "冷食", "沙拉", "轻食", "清爽"],
            "forbidden_candidate_tags": ["热汤", "火锅", "冒菜", "炒菜", "烧烤", "麻辣"],
            "ui_actions": ["render_cards", "show_full_meal_option"],
        },
    },
    {
        "category": "western_craving_plain",
        "history": [],
        "user": "我想吃西餐",
        "context": {"known_preferences": [], "location": "上海全市"},
        "expected": {
            "intent": "western_craving",
            "expected_intents": ["western_craving"],
            "must_infer": ["西餐", "西式简餐/意面/披萨/牛排方向", "不是泛推荐"],
            "must_ask_if_missing": ["想吃意面/披萨/牛排/汉堡还是brunch", "预算和是否要能坐"],
            "must_include": ["明确按西餐筛选", "说明距离/评分/价格综合"],
            "must_avoid": ["海鲜", "日料", "小面", "川湘菜", "火锅", "中餐正餐混推"],
            "expected_candidate_tags": ["西餐", "西式", "意面", "披萨", "牛排", "汉堡", "brunch", "法餐", "美式", "简餐"],
            "forbidden_candidate_tags": ["海鲜", "刺身", "日料", "寿司", "小面", "重庆", "麻辣", "川菜", "湘菜"],
            "ui_actions": ["render_cards", "offer_wishlist", "offer_add_to_map"],
        },
    },
    {
        "category": "single_fast_lunch",
        "history": [],
        "user": "一个人午饭，20分钟内解决，别排队",
        "context": {"known_preferences": [], "location": "静安区"},
        "expected": {
            "intent": "quick_meal",
            "must_infer": ["一人食", "时间紧", "少排队", "午餐"],
            "must_ask_if_missing": ["预算上限"],
            "must_include": ["出餐速度理由", "步行/等待时间风险", "可直接加入地图"],
            "must_avoid": ["高客单慢餐", "需要长时间等位"],
            "ui_actions": ["render_cards", "show_speed_tags"],
        },
    },
    {
        "category": "after_work_tired",
        "history": [],
        "user": "刚下班很累，不想走远，吃点舒服的",
        "context": {"known_preferences": [], "location": "徐汇区"},
        "expected": {
            "intent": "comfort_food",
            "must_infer": ["疲惫", "近距离", "暖胃/舒服", "低决策成本"],
            "must_ask_if_missing": ["预算", "是否想喝汤或主食"],
            "must_include": ["先共情", "少走路理由", "备选不超过3个"],
            "must_avoid": ["过度活泼", "推荐太多家"],
            "ui_actions": ["render_cards", "ask_one_followup"],
        },
    },
    {
        "category": "date_quiet",
        "history": [],
        "user": "两个人约会，想安静一点，人均100以内",
        "context": {"known_preferences": [], "location": "长宁区"},
        "expected": {
            "intent": "date_restaurant",
            "must_infer": ["两人", "约会", "安静", "预算<=100"],
            "must_ask_if_missing": ["是否需要拍照/甜品/饭后散步"],
            "must_include": ["氛围理由", "噪音风险", "适合聊天"],
            "must_avoid": ["翻台快的小店", "大排档式嘈杂"],
            "ui_actions": ["render_cards", "offer_detail"],
        },
    },
    {
        "category": "family_with_parents",
        "history": [],
        "user": "带爸妈吃饭，不要太新潮，环境稳一点",
        "context": {"known_preferences": [], "location": "黄浦区"},
        "expected": {
            "intent": "family_meal",
            "must_infer": ["长辈友好", "环境稳定", "口味稳妥"],
            "must_ask_if_missing": ["预算", "是否需要包间/少走楼梯"],
            "must_include": ["长辈口味理由", "环境和交通说明"],
            "must_avoid": ["网红猎奇", "重口味默认"],
            "ui_actions": ["render_cards", "ask_one_followup"],
        },
    },
    {
        "category": "team_dinner",
        "history": [],
        "user": "同事6个人聚餐，人均80左右，最好能聊天",
        "context": {"known_preferences": [], "location": "浦东新区"},
        "expected": {
            "intent": "group_dinner",
            "must_infer": ["6人", "人均80", "聊天", "聚餐"],
            "must_ask_if_missing": ["是否要包间", "是否有人忌口"],
            "must_include": ["桌型/环境理由", "是否适合多人点菜"],
            "must_avoid": ["单人快餐", "座位拥挤"],
            "ui_actions": ["render_cards", "offer_groupbuy"],
        },
    },
    {
        "category": "late_night_soup",
        "history": [],
        "user": "晚上11点后还能吃吗，想要热汤，不想太油",
        "context": {"known_preferences": ["prefer_light"], "location": "浦东新区"},
        "expected": {
            "intent": "late_night",
            "must_infer": ["夜宵", "营业时间", "热汤", "少油"],
            "must_ask_if_missing": ["堂食还是外卖", "距离上限"],
            "must_include": ["营业风险提醒", "清淡热汤选项"],
            "must_avoid": ["烧烤油炸优先"],
            "ui_actions": ["render_cards", "show_open_status"],
        },
    },
    {
        "category": "fitness_low_cal",
        "history": ["我最近在控糖"],
        "user": "中午想吃轻食，但不要那种吃不饱的",
        "context": {"known_preferences": ["low_sugar"], "location": "静安区"},
        "expected": {
            "intent": "healthy_meal",
            "must_infer": ["控糖", "轻食", "饱腹感"],
            "must_ask_if_missing": ["预算", "是否能接受鸡胸/谷物"],
            "must_include": ["蛋白质/饱腹理由", "避免甜饮"],
            "must_avoid": ["甜品奶茶套餐"],
            "ui_actions": ["render_cards", "show_health_tags"],
        },
    },
    {
        "category": "spicy_but_budget",
        "history": [],
        "user": "想吃辣，但是人均别超过50，别排太久",
        "context": {"known_preferences": [], "location": "杨浦区"},
        "expected": {
            "intent": "spicy_budget",
            "must_infer": ["辣味", "预算<=50", "排队敏感"],
            "must_ask_if_missing": ["几个人", "能接受麻辣程度"],
            "must_include": ["辣度和价格说明", "排队风险"],
            "must_avoid": ["贵价火锅优先"],
            "ui_actions": ["render_cards", "offer_waiting_filter"],
        },
    },
    {
        "category": "avoid_expensive",
        "history": ["这家太贵了，换性价比高的"],
        "user": "继续给我换，预算最好30-40",
        "context": {"known_preferences": ["price_sensitive"], "location": "普陀区"},
        "expected": {
            "intent": "revise_recommendation",
            "must_infer": ["上一轮不满意", "价格敏感", "预算30-40"],
            "must_ask_if_missing": ["是否保留上一轮里某家"],
            "must_include": ["承认并调整", "明确不再推贵店"],
            "must_avoid": ["继续推荐上一轮贵店"],
            "ui_actions": ["replace_cards", "ask_keep_any"],
        },
    },
    {
        "category": "coffee_work",
        "history": [],
        "user": "想找能坐久一点的咖啡店，下午处理工作",
        "context": {"known_preferences": [], "location": "静安区"},
        "expected": {
            "intent": "work_cafe",
            "must_infer": ["办公", "久坐", "下午", "咖啡"],
            "must_ask_if_missing": ["是否需要插座/安静/会议"],
            "must_include": ["座位/插座/噪音理由"],
            "must_avoid": ["翻台快不适合久坐"],
            "ui_actions": ["render_cards", "show_work_friendly_tags"],
        },
    },
    {
        "category": "kid_friendly",
        "history": [],
        "user": "带小朋友吃，别太辣，最好有商场厕所方便",
        "context": {"known_preferences": ["avoid_spicy"], "location": "闵行区"},
        "expected": {
            "intent": "kid_friendly",
            "must_infer": ["带娃", "不辣", "商场便利", "卫生间"],
            "must_ask_if_missing": ["预算", "是否需要儿童座椅"],
            "must_include": ["儿童友好理由", "商场便利"],
            "must_avoid": ["重辣小店", "环境拥挤"],
            "ui_actions": ["render_cards", "offer_map_for_mall"],
        },
    },
    {
        "category": "vegetarian",
        "history": [],
        "user": "今天吃素，有没有不太寡淡的选择",
        "context": {"known_preferences": ["vegetarian_today"], "location": "徐汇区"},
        "expected": {
            "intent": "vegetarian",
            "must_infer": ["素食", "口味不能寡淡"],
            "must_ask_if_missing": ["蛋奶是否可接受", "预算"],
            "must_include": ["素食可选说明", "味型理由"],
            "must_avoid": ["肉类招牌作为主推"],
            "ui_actions": ["render_cards", "ask_one_followup"],
        },
    },
    {
        "category": "allergy",
        "history": [],
        "user": "海鲜过敏，别推荐海鲜，想吃点日料以外的",
        "context": {"known_preferences": ["avoid_seafood"], "location": "虹口区"},
        "expected": {
            "intent": "allergy_safe",
            "must_infer": ["海鲜过敏", "排除日料", "安全优先"],
            "must_ask_if_missing": ["是否需要避开交叉污染"],
            "must_include": ["安全提醒", "非海鲜非日料选择"],
            "must_avoid": ["海鲜", "寿司刺身"],
            "ui_actions": ["render_cards", "persist_avoidance"],
        },
    },
    {
        "category": "breakfast_before_work",
        "history": [],
        "user": "早上上班前买点早餐，最好能带走",
        "context": {"known_preferences": [], "location": "杨浦区"},
        "expected": {
            "intent": "breakfast_takeaway",
            "must_infer": ["早餐", "上班前", "可带走", "速度"],
            "must_ask_if_missing": ["通勤方向", "预算"],
            "must_include": ["出餐速度", "打包友好"],
            "must_avoid": ["慢餐堂食"],
            "ui_actions": ["render_cards", "offer_map_route"],
        },
    },
    {
        "category": "rainy_day_delivery",
        "history": [],
        "user": "下雨了不想出门，附近有啥适合外卖的",
        "context": {"known_preferences": [], "location": "浦东新区"},
        "expected": {
            "intent": "delivery",
            "must_infer": ["雨天", "不出门", "外卖友好"],
            "must_ask_if_missing": ["预算", "想吃主食还是汤"],
            "must_include": ["打包不易翻车", "配送距离"],
            "must_avoid": ["只适合堂食的菜"],
            "ui_actions": ["render_cards", "show_delivery_tags"],
        },
    },
    {
        "category": "solo_not_awkward",
        "history": [],
        "user": "一个人吃饭，不想太尴尬，坐吧台也行",
        "context": {"known_preferences": [], "location": "黄浦区"},
        "expected": {
            "intent": "solo_comfort",
            "must_infer": ["一人食", "不尴尬", "吧台/小桌"],
            "must_ask_if_missing": ["预算", "是否赶时间"],
            "must_include": ["一人友好座位理由", "心理舒适"],
            "must_avoid": ["大桌聚餐店"],
            "ui_actions": ["render_cards", "show_solo_tags"],
        },
    },
    {
        "category": "business_meeting",
        "history": [],
        "user": "约客户吃饭，不能太吵，最好体面一点",
        "context": {"known_preferences": [], "location": "陆家嘴"},
        "expected": {
            "intent": "business_meal",
            "must_infer": ["商务", "体面", "安静"],
            "must_ask_if_missing": ["预算", "是否需要包间/发票"],
            "must_include": ["环境可靠", "交通/停车"],
            "must_avoid": ["街边小吃优先"],
            "ui_actions": ["render_cards", "offer_detail"],
        },
    },
    {
        "category": "student_budget",
        "history": [],
        "user": "学生党，预算15左右，要吃饱",
        "context": {"known_preferences": ["budget_low"], "location": "杨浦区"},
        "expected": {
            "intent": "low_budget_full",
            "must_infer": ["预算低", "吃饱", "学生"],
            "must_ask_if_missing": ["是否能接受排队"],
            "must_include": ["饱腹性", "价格"],
            "must_avoid": ["轻食小份量优先"],
            "ui_actions": ["render_cards", "show_budget_tags"],
        },
    },
    {
        "category": "tourist_local_food",
        "history": [],
        "user": "外地朋友来上海，想吃点有本地特色但别太贵",
        "context": {"known_preferences": [], "location": "黄浦区"},
        "expected": {
            "intent": "local_specialty",
            "must_infer": ["游客", "上海特色", "价格别太贵"],
            "must_ask_if_missing": ["人数", "是否介意排队"],
            "must_include": ["本地特色理由", "游客友好"],
            "must_avoid": ["全国连锁无特色优先"],
            "ui_actions": ["render_cards", "offer_map"],
        },
    },
    {
        "category": "not_sure_mood",
        "history": [],
        "user": "我也不知道吃什么，就是有点烦",
        "context": {"known_preferences": [], "location": "静安区"},
        "expected": {
            "intent": "mood_discovery",
            "must_infer": ["情绪不佳", "需求模糊"],
            "must_ask_if_missing": ["想被安慰还是快速决定", "预算"],
            "must_include": ["共情", "少量选项", "低压力追问"],
            "must_avoid": ["直接抛很多餐厅"],
            "ui_actions": ["ask_clarifying_question", "maybe_render_one_safe_card"],
        },
    },
    {
        "category": "need_recommendation_explain",
        "history": ["你推荐了豆舍咖啡"],
        "user": "为什么是这家，不是旁边那家？",
        "context": {"known_preferences": ["work_cafe"], "location": "静安区"},
        "expected": {
            "intent": "explain_recommendation",
            "must_infer": ["用户在比较", "需要解释排序"],
            "must_ask_if_missing": [],
            "must_include": ["明确比较维度", "承认可替代选项"],
            "must_avoid": ["空泛说更好"],
            "ui_actions": ["highlight_card", "offer_compare"],
        },
    },
    {
        "category": "want_keep_some",
        "history": ["上一轮推荐了A、B、C三家"],
        "user": "A先留着，另外两个换一下",
        "context": {"known_preferences": [], "location": "徐汇区"},
        "expected": {
            "intent": "partial_replace",
            "must_infer": ["保留A", "替换B/C"],
            "must_ask_if_missing": ["替换方向是否因为价格/距离/口味"],
            "must_include": ["确认保留", "新推荐不覆盖保留项"],
            "must_avoid": ["把A也删除"],
            "ui_actions": ["keep_selected_card", "replace_other_cards"],
        },
    },
    {
        "category": "wishlist_from_chat",
        "history": ["推荐了三家餐厅"],
        "user": "把第二家放进心愿单，其他先不要",
        "context": {"known_preferences": [], "location": "杨浦区"},
        "expected": {
            "intent": "wishlist_single",
            "must_infer": ["只加入第二家", "不批量加入"],
            "must_ask_if_missing": [],
            "must_include": ["确认已加入哪一家"],
            "must_avoid": ["把三家全加入"],
            "ui_actions": ["wishlist_add_one", "refresh_wishlist"],
        },
    },
    {
        "category": "dislike_last_restaurant",
        "history": ["刚推荐过一家川菜"],
        "user": "这个不行，太重口了",
        "context": {"known_preferences": [], "location": "普陀区"},
        "expected": {
            "intent": "negative_feedback",
            "must_infer": ["上一家不合适", "重口需降低"],
            "must_ask_if_missing": ["想换清淡还是换菜系"],
            "must_include": ["承认调整", "记录避开重口"],
            "must_avoid": ["继续重辣"],
            "ui_actions": ["replace_cards", "persist_avoidance"],
        },
    },
    {
        "category": "prefer_queue_low",
        "history": [],
        "user": "评分不用最高，排队少更重要",
        "context": {"known_preferences": [], "location": "长宁区"},
        "expected": {
            "intent": "queue_priority",
            "must_infer": ["排队优先级高于评分"],
            "must_ask_if_missing": ["预算", "当前可接受等待时间"],
            "must_include": ["排序依据变化", "等待风险"],
            "must_avoid": ["只按评分排序"],
            "ui_actions": ["rerank_cards", "show_queue_reason"],
        },
    },
    {
        "category": "need_social_buzz",
        "history": [],
        "user": "看看社区里最近讨论最多的店，少踩雷",
        "context": {"known_preferences": [], "location": "杨浦区"},
        "expected": {
            "intent": "community_buzz",
            "must_infer": ["社区热度", "少踩雷", "口碑"],
            "must_ask_if_missing": ["预算/口味"],
            "must_include": ["热帖/评价依据", "风险提醒"],
            "must_avoid": ["无依据地说很火"],
            "ui_actions": ["render_cards", "link_community_posts"],
        },
    },
    {
        "category": "ask_menu",
        "history": ["用户打开了某餐厅详情"],
        "user": "这家有什么必点，别太贵",
        "context": {"known_preferences": ["price_sensitive"], "location": "静安区"},
        "expected": {
            "intent": "menu_advice",
            "must_infer": ["菜单建议", "价格敏感"],
            "must_ask_if_missing": [],
            "must_include": ["必点菜", "价格/份量建议"],
            "must_avoid": ["推荐高价招牌而不解释"],
            "ui_actions": ["show_menu_items", "offer_add_to_wishlist"],
        },
    },
    {
        "category": "need_reservation",
        "history": [],
        "user": "晚上7点四个人，会不会要等位？",
        "context": {"known_preferences": [], "location": "徐汇区"},
        "expected": {
            "intent": "reservation_waiting",
            "must_infer": ["晚高峰", "4人", "等位风险"],
            "must_ask_if_missing": ["目标餐厅/预算"],
            "must_include": ["等位风险", "备选策略"],
            "must_avoid": ["保证无需等位"],
            "ui_actions": ["ask_target_or_render_options"],
        },
    },
    {
        "category": "multi_preference_conflict",
        "history": [],
        "user": "想吃火锅但又想清淡一点，预算也别太高",
        "context": {"known_preferences": [], "location": "普陀区"},
        "expected": {
            "intent": "resolve_conflict",
            "must_infer": ["火锅欲望", "清淡", "预算"],
            "must_ask_if_missing": ["能否接受汤锅/冒菜/小火锅"],
            "must_include": ["解释折中方案", "给选择分支"],
            "must_avoid": ["直接推荐重辣火锅"],
            "ui_actions": ["ask_clarifying_question", "render_compromise_cards"],
        },
    },
    {
        "category": "repeat_user_memory",
        "history": ["用户多次说喜欢清淡、轻食、近一点"],
        "user": "今天照旧帮我看看",
        "context": {"known_preferences": ["prefer_light", "distance_sensitive"], "location": "静安区"},
        "expected": {
            "intent": "use_memory",
            "must_infer": ["沿用历史偏好", "少追问"],
            "must_ask_if_missing": ["是否预算还在30以内"],
            "must_include": ["说明沿用偏好", "近+清淡"],
            "must_avoid": ["重新从零问很多问题"],
            "ui_actions": ["render_cards", "offer_map"],
        },
    },
    {
        "category": "post_meal_activity_normal",
        "history": [],
        "user": "吃完想散步，但我先在普通agent里问",
        "context": {"known_preferences": [], "location": "黄浦区"},
        "expected": {
            "intent": "handoff_to_map",
            "must_infer": ["餐后安排", "空间需求"],
            "must_ask_if_missing": ["散步多久/是否要江边或商场"],
            "must_include": ["建议进入地图综合选择"],
            "must_avoid": ["只给餐厅不提路线"],
            "ui_actions": ["render_cards", "offer_fullscreen_map"],
        },
    },
]


MAP_AGENT_SEEDS: list[dict[str, Any]] = [
    {
        "category": "nearby_default_map",
        "history": [],
        "user": "我刚打开地图，先看看附近少踩雷的三家",
        "context": {"location": [31.2304, 121.4737], "map_center": "黄浦区"},
        "expected": {
            "intent": "map_recommend_nearby",
            "must_infer": ["当前地图位置", "附近", "少踩雷"],
            "must_ask_if_missing": ["预算/口味可作为追问"],
            "must_include": ["地图点位", "距离线", "推荐卡片一致"],
            "must_avoid": ["推荐文字和点位不一致"],
            "map_actions": ["clear_old_restaurant_points", "add_restaurant_points", "fit_bounds"],
            "ui_actions": ["render_map_cards", "ask_add_to_wishlist"],
        },
    },
    {
        "category": "subway_after_meal",
        "history": [],
        "user": "吃完我要坐地铁，帮我找别太绕的",
        "context": {"location": [31.1935, 121.4367], "map_center": "徐汇区"},
        "expected": {
            "intent": "route_to_subway",
            "must_infer": ["餐后坐地铁", "少绕路", "空间规划"],
            "must_ask_if_missing": ["目标地铁线/方向", "预算"],
            "must_include": ["餐厅到地铁的空间理由", "路线式方案"],
            "must_avoid": ["只按评分推荐"],
            "map_actions": ["mark_user", "mark_restaurants", "mark_subway_stations", "draw_route_arcs"],
            "ui_actions": ["show_plan_cards", "highlight_selected_arc"],
        },
    },
    {
        "category": "mall_after_meal",
        "history": [],
        "user": "吃完想逛商场，顺路一点",
        "context": {"location": [31.2215, 121.5440], "map_center": "浦东新区"},
        "expected": {
            "intent": "meal_plus_mall",
            "must_infer": ["餐后商场", "顺路", "空间组合"],
            "must_ask_if_missing": ["想逛多久/是否要亲子或购物"],
            "must_include": ["餐厅+商场组合方案"],
            "must_avoid": ["商场和餐厅距离脱节"],
            "map_actions": ["mark_malls", "mark_restaurants", "draw_restaurant_to_mall"],
            "ui_actions": ["show_plan_cards", "offer_wishlist"],
        },
    },
    {
        "category": "exhibition_before_meal",
        "history": [],
        "user": "我之后要去展会，先找路上能吃的",
        "context": {"location": [31.2204, 121.4246], "map_center": "长宁区"},
        "expected": {
            "intent": "meal_on_route_to_event",
            "must_infer": ["后续展会", "顺路吃饭", "时间约束"],
            "must_ask_if_missing": ["展会地点/入场时间", "预算"],
            "must_include": ["沿路选择", "时间风险"],
            "must_avoid": ["反方向推荐"],
            "map_actions": ["ask_destination_if_missing", "mark_event", "mark_restaurants_on_route"],
            "ui_actions": ["ask_clarifying_question", "show_route_options"],
        },
    },
    {
        "category": "study_after_meal",
        "history": [],
        "user": "吃完要找地方自习，安静一点",
        "context": {"location": [31.2290, 121.4598], "map_center": "静安区"},
        "expected": {
            "intent": "meal_plus_study",
            "must_infer": ["餐后自习", "安静", "久坐"],
            "must_ask_if_missing": ["需要插座吗", "预算"],
            "must_include": ["餐厅+自习/咖啡点", "安静理由"],
            "must_avoid": ["嘈杂聚餐店"],
            "map_actions": ["mark_restaurants", "mark_study_spots", "draw_sequence"],
            "ui_actions": ["show_plan_cards", "offer_fullscreen_map"],
        },
    },
    {
        "category": "parking_needed",
        "history": [],
        "user": "我开车，找停车方便的地方吃饭",
        "context": {"location": [31.2494, 121.3976], "map_center": "普陀区"},
        "expected": {
            "intent": "parking_friendly",
            "must_infer": ["开车", "停车便利"],
            "must_ask_if_missing": ["预计几点到", "是否接受商场停车"],
            "must_include": ["停车点/商场停车理由"],
            "must_avoid": ["只适合步行的小巷"],
            "map_actions": ["mark_parking_or_mall", "mark_restaurants", "draw_walking_from_parking"],
            "ui_actions": ["show_map_annotations"],
        },
    },
    {
        "category": "avoid_traffic",
        "history": [],
        "user": "现在有点堵，帮我别选要穿过主干道的",
        "context": {"location": [31.2646, 121.5051], "map_center": "虹口区"},
        "expected": {
            "intent": "avoid_traffic_route",
            "must_infer": ["拥堵", "避开主干道", "路线便利"],
            "must_ask_if_missing": ["步行/骑车/打车"],
            "must_include": ["路线风险说明", "同侧/少过街优先"],
            "must_avoid": ["直线距离近但过街复杂"],
            "map_actions": ["mark_barriers", "rank_by_route_convenience"],
            "ui_actions": ["show_route_reason"],
        },
    },
    {
        "category": "wishlist_plan_map",
        "history": ["心愿单里有3家店"],
        "user": "把心愿单放到地图上，我想比较一下",
        "context": {"location": [31.2914, 121.5070], "map_center": "杨浦区"},
        "expected": {
            "intent": "wishlist_to_map",
            "must_infer": ["心愿单规划", "比较选择"],
            "must_ask_if_missing": ["按距离/价格/下一站排序"],
            "must_include": ["只展示心愿单点位", "比较维度"],
            "must_avoid": ["混入无关新餐厅"],
            "map_actions": ["clear_old_points", "add_wishlist_points", "fit_bounds"],
            "ui_actions": ["open_wishlist_panel", "show_plan_cards"],
        },
    },
    {
        "category": "replace_map_recommendations",
        "history": ["地图上已有上一轮餐厅点位"],
        "user": "这批都不太行，重新推荐一批清淡的",
        "context": {"location": [31.2290, 121.4598], "map_center": "静安区"},
        "expected": {
            "intent": "replace_map_points",
            "must_infer": ["清空旧推荐", "清淡偏好"],
            "must_ask_if_missing": ["是否保留心愿单里的店"],
            "must_include": ["说明已替换地图点位"],
            "must_avoid": ["旧点位继续混在地图上"],
            "map_actions": ["clear_old_restaurant_points", "add_new_restaurant_points"],
            "ui_actions": ["ask_keep_wishlist", "render_map_cards"],
        },
    },
    {
        "category": "keep_one_on_map",
        "history": ["地图推荐了A、B、C"],
        "user": "A保留，B和C换掉，最好离地铁近",
        "context": {"location": [31.1935, 121.4367], "map_center": "徐汇区"},
        "expected": {
            "intent": "partial_map_replace",
            "must_infer": ["保留A", "替换B/C", "地铁近"],
            "must_ask_if_missing": ["目标地铁方向"],
            "must_include": ["保留点位说明", "新点位靠近地铁"],
            "must_avoid": ["清掉A"],
            "map_actions": ["keep_selected_point", "replace_other_points", "mark_subway"],
            "ui_actions": ["highlight_kept_point"],
        },
    },
    {
        "category": "walkable_10_minutes",
        "history": [],
        "user": "只看步行10分钟以内，预算40",
        "context": {"location": [31.2304, 121.4737], "map_center": "黄浦区"},
        "expected": {
            "intent": "distance_budget_filter",
            "must_infer": ["步行<=10分钟", "预算40"],
            "must_ask_if_missing": ["口味偏好"],
            "must_include": ["距离圈/步行时间", "预算匹配"],
            "must_avoid": ["超过10分钟却不解释"],
            "map_actions": ["draw_radius", "filter_restaurants", "fit_bounds"],
            "ui_actions": ["render_filtered_map_cards"],
        },
    },
    {
        "category": "two_stage_date",
        "history": [],
        "user": "约会吃饭，吃完想散步，别太商业化",
        "context": {"location": [31.2304, 121.4737], "map_center": "黄浦区"},
        "expected": {
            "intent": "date_route_plan",
            "must_infer": ["约会", "饭后散步", "避开商业化"],
            "must_ask_if_missing": ["预算", "想安静还是热闹"],
            "must_include": ["餐厅+散步路线"],
            "must_avoid": ["纯商场路线"],
            "map_actions": ["mark_walkable_area", "mark_restaurants", "draw_sequence"],
            "ui_actions": ["show_route_options"],
        },
    },
    {
        "category": "parent_kid_mall_play",
        "history": [],
        "user": "带孩子吃完想去商场玩一会儿",
        "context": {"location": [31.1128, 121.3817], "map_center": "闵行区"},
        "expected": {
            "intent": "kid_mall_route",
            "must_infer": ["带娃", "餐后商场游乐", "亲子便利"],
            "must_ask_if_missing": ["孩子年龄", "预算/忌口"],
            "must_include": ["亲子餐厅+商场/游乐标注"],
            "must_avoid": ["酒吧/重辣/拥挤"],
            "map_actions": ["mark_malls", "mark_kid_friendly_restaurants", "draw_route"],
            "ui_actions": ["show_family_plan"],
        },
    },
    {
        "category": "commute_home",
        "history": [],
        "user": "吃完要回家，尽量方便打车或坐地铁",
        "context": {"location": [31.2494, 121.3976], "map_center": "普陀区"},
        "expected": {
            "intent": "home_commute_after_meal",
            "must_infer": ["餐后回家", "交通便利"],
            "must_ask_if_missing": ["家所在方向/线路"],
            "must_include": ["交通节点标注", "回程便利比较"],
            "must_avoid": ["深入小巷不方便离开"],
            "map_actions": ["mark_subway_or_taxi_points", "rank_by_exit_convenience"],
            "ui_actions": ["ask_destination", "show_plan_cards"],
        },
    },
    {
        "category": "airport_train_station",
        "history": [],
        "user": "我要赶火车，找一个路上能快速吃的",
        "context": {"location": [31.2290, 121.4598], "map_center": "静安区"},
        "expected": {
            "intent": "transit_deadline",
            "must_infer": ["赶火车", "时间紧", "沿路快速吃"],
            "must_ask_if_missing": ["车站/发车时间", "交通方式"],
            "must_include": ["时间风险", "快餐/打包"],
            "must_avoid": ["慢餐", "反方向"],
            "map_actions": ["ask_destination_if_missing", "mark_route_food", "mark_station"],
            "ui_actions": ["ask_clarifying_question"],
        },
    },
    {
        "category": "meeting_before_food",
        "history": [],
        "user": "我1小时后开会，附近吃个不留味的",
        "context": {"location": [31.2215, 121.5440], "map_center": "浦东新区"},
        "expected": {
            "intent": "pre_meeting_meal",
            "must_infer": ["1小时后", "不留味", "商务前"],
            "must_ask_if_missing": ["预算", "是否要咖啡"],
            "must_include": ["低气味/快速", "时间安排"],
            "must_avoid": ["火锅烧烤重油烟"],
            "map_actions": ["filter_by_time", "mark_nearby_quick_options"],
            "ui_actions": ["show_time_plan"],
        },
    },
    {
        "category": "need_landmarks",
        "history": [],
        "user": "把附近地铁站和商场也标出来，我想一起看",
        "context": {"location": [31.2646, 121.5051], "map_center": "虹口区"},
        "expected": {
            "intent": "show_landmarks",
            "must_infer": ["用户主动要求地标", "空间比较"],
            "must_ask_if_missing": ["是否按餐后安排排序"],
            "must_include": ["地铁站/商场标注说明"],
            "must_avoid": ["只展示餐厅"],
            "map_actions": ["mark_subway_stations", "mark_malls", "keep_restaurant_points"],
            "ui_actions": ["show_landmark_legend"],
        },
    },
    {
        "category": "selected_restaurant_route",
        "history": ["用户点击了地图上的某餐厅"],
        "user": "就这家，帮我看看吃完去哪最顺",
        "context": {"location": [31.1935, 121.4367], "map_center": "徐汇区"},
        "expected": {
            "intent": "post_meal_from_selected",
            "must_infer": ["已有选中餐厅", "餐后去处规划"],
            "must_ask_if_missing": ["想逛/坐/回家/地铁"],
            "must_include": ["围绕选中餐厅规划"],
            "must_avoid": ["重新随机推荐餐厅"],
            "map_actions": ["highlight_selected_restaurant", "mark_nearby_next_places"],
            "ui_actions": ["ask_next_activity"],
        },
    },
    {
        "category": "compare_two_restaurants_map",
        "history": ["地图上有两家候选"],
        "user": "这两家哪个更适合我吃完去地铁？",
        "context": {"location": [31.2914, 121.5070], "map_center": "杨浦区"},
        "expected": {
            "intent": "compare_candidates_spatial",
            "must_infer": ["二选一", "去地铁"],
            "must_ask_if_missing": ["目标地铁站/线路"],
            "must_include": ["空间比较", "推荐结论"],
            "must_avoid": ["只比较口味"],
            "map_actions": ["highlight_two_routes", "mark_subway", "select_better_route"],
            "ui_actions": ["show_comparison_card"],
        },
    },
    {
        "category": "rain_map",
        "history": [],
        "user": "下雨了，最好少走露天路",
        "context": {"location": [31.2290, 121.4598], "map_center": "静安区"},
        "expected": {
            "intent": "rain_sheltered_route",
            "must_infer": ["雨天", "少露天", "路线遮蔽"],
            "must_ask_if_missing": ["是否接受商场内餐饮"],
            "must_include": ["商场/连廊优先", "步行暴露风险"],
            "must_avoid": ["露天长距离路线"],
            "map_actions": ["mark_malls", "rank_by_shelter", "draw_short_routes"],
            "ui_actions": ["show_weather_sensitive_plan"],
        },
    },
    {
        "category": "elderly_route",
        "history": [],
        "user": "带老人，别走太多路，也别上下楼麻烦",
        "context": {"location": [31.2304, 121.4737], "map_center": "黄浦区"},
        "expected": {
            "intent": "elderly_accessible",
            "must_infer": ["老人", "少走路", "无障碍/少楼梯"],
            "must_ask_if_missing": ["是否需要电梯/包间"],
            "must_include": ["动线便利", "步行距离"],
            "must_avoid": ["楼梯多/拥挤小店"],
            "map_actions": ["rank_by_accessibility", "mark_dropoff_points"],
            "ui_actions": ["show_accessibility_notes"],
        },
    },
    {
        "category": "sports_after_meal",
        "history": [],
        "user": "吃完想去健身房，别吃太撑",
        "context": {"location": [31.2204, 121.4246], "map_center": "长宁区"},
        "expected": {
            "intent": "meal_before_gym",
            "must_infer": ["餐后健身", "别太撑", "轻负担"],
            "must_ask_if_missing": ["健身房位置/时间"],
            "must_include": ["轻食/蛋白质", "到健身房路线"],
            "must_avoid": ["油腻大餐"],
            "map_actions": ["mark_gym_if_known", "mark_light_meal_options"],
            "ui_actions": ["ask_destination", "show_light_options"],
        },
    },
    {
        "category": "movie_after_meal",
        "history": [],
        "user": "吃完要看电影，找影院附近的",
        "context": {"location": [31.1128, 121.3817], "map_center": "闵行区"},
        "expected": {
            "intent": "meal_plus_cinema",
            "must_infer": ["电影", "影院附近", "时间衔接"],
            "must_ask_if_missing": ["影院/开场时间"],
            "must_include": ["影院标注", "用餐时长风险"],
            "must_avoid": ["离影院远的店"],
            "map_actions": ["mark_cinemas", "mark_restaurants_near_cinema", "draw_sequence"],
            "ui_actions": ["ask_time"],
        },
    },
    {
        "category": "tour_route",
        "history": [],
        "user": "朋友第一次来上海，吃完想看看附近景点",
        "context": {"location": [31.2304, 121.4737], "map_center": "黄浦区"},
        "expected": {
            "intent": "tourist_meal_route",
            "must_infer": ["游客", "餐后景点", "上海特色"],
            "must_ask_if_missing": ["想经典景点还是轻松散步"],
            "must_include": ["本地特色餐厅+景点"],
            "must_avoid": ["纯连锁无特色"],
            "map_actions": ["mark_landmarks", "mark_local_food", "draw_tour_route"],
            "ui_actions": ["show_tour_plan"],
        },
    },
    {
        "category": "hotel_nearby",
        "history": [],
        "user": "我住酒店，晚上不想走太远，有没有安全一点的路线",
        "context": {"location": [31.2215, 121.5440], "map_center": "浦东新区"},
        "expected": {
            "intent": "hotel_nearby_safe_route",
            "must_infer": ["酒店附近", "夜间", "安全路线"],
            "must_ask_if_missing": ["酒店位置/可接受距离"],
            "must_include": ["近距离", "路线安全感"],
            "must_avoid": ["夜间偏僻路线"],
            "map_actions": ["mark_hotel_if_known", "rank_by_night_safety"],
            "ui_actions": ["ask_location_if_needed"],
        },
    },
    {
        "category": "multi_stop_day_plan",
        "history": [],
        "user": "帮我排一个吃饭、咖啡、逛店的顺序",
        "context": {"location": [31.2290, 121.4598], "map_center": "静安区"},
        "expected": {
            "intent": "multi_stop_plan",
            "must_infer": ["多站点", "顺序规划", "吃饭+咖啡+逛店"],
            "must_ask_if_missing": ["总时长/预算/兴趣"],
            "must_include": ["路线顺序", "每站目的"],
            "must_avoid": ["只推荐餐厅"],
            "map_actions": ["mark_multi_stop", "draw_sequence_route"],
            "ui_actions": ["show_itinerary_cards"],
        },
    },
    {
        "category": "map_no_location",
        "history": [],
        "user": "帮我规划附近吃饭路线",
        "context": {"location": None, "map_center": None},
        "expected": {
            "intent": "need_location",
            "must_infer": ["缺少位置", "地图规划无法直接做"],
            "must_ask_if_missing": ["定位或搜索地点"],
            "must_include": ["请先定位/搜索地点"],
            "must_avoid": ["假装知道用户位置"],
            "map_actions": ["request_location_or_search"],
            "ui_actions": ["focus_location_search"],
        },
    },
    {
        "category": "map_conversation_clarify",
        "history": [],
        "user": "帮我选一个吃完还方便下一步的",
        "context": {"location": [31.1935, 121.4367], "map_center": "徐汇区"},
        "expected": {
            "intent": "clarify_next_step",
            "must_infer": ["下一步未明确", "需要追问"],
            "must_ask_if_missing": ["下一步是地铁/商场/自习/回家/见朋友"],
            "must_include": ["给可选方向按钮"],
            "must_avoid": ["直接做路线假设"],
            "map_actions": ["hold_current_points"],
            "ui_actions": ["show_quick_replies"],
        },
    },
    {
        "category": "map_budget_then_space",
        "history": [],
        "user": "预算30以内，还要离商场近",
        "context": {"location": [31.1128, 121.3817], "map_center": "闵行区"},
        "expected": {
            "intent": "budget_plus_mall",
            "must_infer": ["预算<=30", "商场附近"],
            "must_ask_if_missing": ["口味/人数"],
            "must_include": ["预算和商场距离同时解释"],
            "must_avoid": ["只满足一个条件"],
            "map_actions": ["mark_malls", "filter_restaurants_by_budget", "draw_distance"],
            "ui_actions": ["show_compromise_notes"],
        },
    },
    {
        "category": "map_no_spicy_memory",
        "history": ["用户说过不吃辣"],
        "user": "地图上重新推荐几家，别忘了我的口味",
        "context": {"location": [31.2646, 121.5051], "map_center": "虹口区", "known_preferences": ["avoid_spicy"]},
        "expected": {
            "intent": "map_use_memory",
            "must_infer": ["沿用不吃辣", "重新推荐"],
            "must_ask_if_missing": ["预算/距离上限"],
            "must_include": ["说明避开辣味", "更新地图点位"],
            "must_avoid": ["川湘火锅优先"],
            "map_actions": ["clear_old_points", "add_non_spicy_points"],
            "ui_actions": ["render_map_cards"],
        },
    },
    {
        "category": "map_selected_arc",
        "history": ["地图上有多条餐厅距离线"],
        "user": "点开第二家看看",
        "context": {"location": [31.2914, 121.5070], "map_center": "杨浦区"},
        "expected": {
            "intent": "select_map_restaurant",
            "must_infer": ["用户选择地图点位", "需要高亮"],
            "must_ask_if_missing": [],
            "must_include": ["基础信息弹窗", "高亮对应路线"],
            "must_avoid": ["遮挡其他点位"],
            "map_actions": ["highlight_selected_marker", "highlight_selected_arc", "open_popover"],
            "ui_actions": ["show_detail_actions"],
        },
    },
    {
        "category": "map_remove_point",
        "history": ["地图上有多家推荐"],
        "user": "这家取消标记，其他保留",
        "context": {"location": [31.2304, 121.4737], "map_center": "黄浦区"},
        "expected": {
            "intent": "remove_one_map_point",
            "must_infer": ["只取消当前点位", "保留其他"],
            "must_ask_if_missing": [],
            "must_include": ["确认已取消"],
            "must_avoid": ["清空所有点位"],
            "map_actions": ["remove_selected_marker", "recalculate_bounds"],
            "ui_actions": ["update_map_cards"],
        },
    },
    {
        "category": "map_plan_from_agent_cards",
        "history": ["普通Agent推荐了三家卡片"],
        "user": "把这三家放地图上，我看方位",
        "context": {"location": [31.2290, 121.4598], "map_center": "静安区"},
        "expected": {
            "intent": "handoff_cards_to_map",
            "must_infer": ["普通Agent到地图Agent", "三家卡片"],
            "must_ask_if_missing": [],
            "must_include": ["地图已更新说明", "方位/距离比较"],
            "must_avoid": ["重新换一批餐厅"],
            "map_actions": ["open_fullscreen_map", "add_given_card_points", "fit_bounds"],
            "ui_actions": ["show_plan_cards"],
        },
    },
    {
        "category": "map_after_concert",
        "history": [],
        "user": "看完演出可能很晚，附近能吃啥，别走偏路",
        "context": {"location": [31.2204, 121.4246], "map_center": "长宁区"},
        "expected": {
            "intent": "post_event_late_food",
            "must_infer": ["演出后", "较晚", "安全/不偏路"],
            "must_ask_if_missing": ["演出地点/散场时间"],
            "must_include": ["营业时间", "路线安全"],
            "must_avoid": ["偏僻路线"],
            "map_actions": ["mark_event", "mark_late_open_restaurants", "draw_safe_routes"],
            "ui_actions": ["ask_time_if_missing"],
        },
    },
    {
        "category": "map_shopping_rest",
        "history": [],
        "user": "逛累了，找个附近能坐下休息吃点的",
        "context": {"location": [31.1128, 121.3817], "map_center": "闵行区"},
        "expected": {
            "intent": "rest_after_shopping",
            "must_infer": ["逛累", "能坐", "附近"],
            "must_ask_if_missing": ["想正餐还是甜品/咖啡"],
            "must_include": ["座位/休息友好", "距离"],
            "must_avoid": ["站食/排队长"],
            "map_actions": ["mark_restaurants", "mark_mall_context", "rank_by_seating"],
            "ui_actions": ["show_rest_options"],
        },
    },
    {
        "category": "map_transfer_station",
        "history": [],
        "user": "我在换乘站附近，想找不出站太远的",
        "context": {"location": [31.2304, 121.4737], "map_center": "黄浦区"},
        "expected": {
            "intent": "transfer_station_food",
            "must_infer": ["换乘站", "不走远"],
            "must_ask_if_missing": ["哪个站/是否出站"],
            "must_include": ["站点距离", "出站复杂度"],
            "must_avoid": ["远离站点"],
            "map_actions": ["mark_station_exits", "rank_by_exit_distance"],
            "ui_actions": ["ask_station_if_missing"],
        },
    },
    {
        "category": "map_heat_and_distance",
        "history": [],
        "user": "不要只看最近，也看看社区热度",
        "context": {"location": [31.2914, 121.5070], "map_center": "杨浦区"},
        "expected": {
            "intent": "spatial_social_rerank",
            "must_infer": ["距离+社区热度综合"],
            "must_ask_if_missing": ["预算/口味"],
            "must_include": ["综合排序解释"],
            "must_avoid": ["只按距离"],
            "map_actions": ["rerank_points", "show_heat_badges"],
            "ui_actions": ["show_ranking_reason"],
        },
    },
    {
        "category": "map_final_decision",
        "history": ["用户已比较三家"],
        "user": "帮我直接拍板吧",
        "context": {"location": [31.1935, 121.4367], "map_center": "徐汇区"},
        "expected": {
            "intent": "make_decision",
            "must_infer": ["用户需要最终决策", "已有候选"],
            "must_ask_if_missing": [],
            "must_include": ["明确推荐一家", "为什么不是另外两家", "下一步动作"],
            "must_avoid": ["继续含糊给多个选项"],
            "map_actions": ["highlight_final_choice", "dim_other_points"],
            "ui_actions": ["show_final_card", "offer_navigation"],
        },
    },
]


def _make_expected(
    intent: str,
    must_infer: list[str],
    must_ask_if_missing: list[str],
    must_include: list[str],
    must_avoid: list[str],
    ui_actions: list[str],
    **extra: Any,
) -> dict[str, Any]:
    expected = {
        "intent": intent,
        "must_infer": must_infer,
        "must_ask_if_missing": must_ask_if_missing,
        "must_include": must_include,
        "must_avoid": must_avoid,
        "ui_actions": ui_actions,
    }
    expected.update(extra)
    return expected


def _normal_seed(
    category: str,
    user: str,
    intent: str,
    must_infer: list[str],
    must_ask_if_missing: list[str],
    must_include: list[str],
    must_avoid: list[str],
    ui_actions: list[str],
    known_preferences: list[str] | None = None,
    location: str = "上海全市",
    history: list[str] | None = None,
    **extra: Any,
) -> dict[str, Any]:
    return {
        "category": category,
        "history": history or [],
        "user": user,
        "context": {"known_preferences": known_preferences or [], "location": location},
        "expected": _make_expected(
            intent,
            must_infer,
            must_ask_if_missing,
            must_include,
            must_avoid,
            ui_actions,
            **extra,
        ),
    }


def _map_seed(
    category: str,
    user: str,
    intent: str,
    must_infer: list[str],
    must_ask_if_missing: list[str],
    must_include: list[str],
    must_avoid: list[str],
    map_actions: list[str],
    ui_actions: list[str],
    location: list[float] | None = None,
    map_center: str | None = "静安区",
    history: list[str] | None = None,
    known_preferences: list[str] | None = None,
    **extra: Any,
) -> dict[str, Any]:
    context: dict[str, Any] = {"location": location or [31.2304, 121.4737], "map_center": map_center}
    if known_preferences:
        context["known_preferences"] = known_preferences
    return {
        "category": category,
        "history": history or [],
        "user": user,
        "context": context,
        "expected": {
            **_make_expected(
                intent,
                must_infer,
                must_ask_if_missing,
                must_include,
                must_avoid,
                ui_actions,
                **extra,
            ),
            "map_actions": map_actions,
        },
    }


PRODUCT_AGENT_SEEDS: list[dict[str, Any]] = [
    _normal_seed(
        "product_community_intro",
        "社区圈是什么，有什么用",
        "product_community_help",
        ["用户问产品功能", "社区圈不是餐厅推荐请求"],
        [],
        ["解释社区圈用途", "说明可看附近帖子/评价/热帖", "提示如何进入"],
        ["直接推荐餐厅", "生成餐厅卡片"],
        ["answer_product_help", "no_restaurant_cards"],
        no_recommendations=True,
    ),
    _normal_seed(
        "product_community_related",
        "社群相关事项都有哪些",
        "product_community_help",
        ["社群相关", "产品功能咨询", "不是餐厅推荐请求"],
        [],
        ["解释社区圈/社群承接内容", "说明热帖/探店/求推荐/评价"],
        ["直接推荐餐厅", "兜底餐厅卡片"],
        ["answer_product_help", "no_restaurant_cards"],
        no_recommendations=True,
    ),
    _normal_seed(
        "product_community_content",
        "社区里一般能看什么内容",
        "product_community_help",
        ["社区内容", "产品功能咨询"],
        [],
        ["说明探店、评价、热帖、求推荐", "说明和推荐的关系"],
        ["直接生成餐厅卡片"],
        ["answer_product_help", "no_restaurant_cards"],
        no_recommendations=True,
    ),
    _normal_seed(
        "product_community_post",
        "我想发探店帖子，怎么发",
        "product_community_post_help",
        ["发帖帮助", "探店内容结构"],
        [],
        ["说明发帖入口", "建议写体验/排队/适合人群/避雷点"],
        ["推荐餐厅替代回答"],
        ["answer_product_help", "guide_post_creation"],
        no_recommendations=True,
    ),
    _normal_seed(
        "product_group_vs_community",
        "社群和社区圈是一回事吗",
        "product_community_help",
        ["概念解释", "社群/社区圈关系"],
        [],
        ["解释社群/社区圈承接附近讨论", "说明帖子和评价入口"],
        ["推荐餐厅代替说明"],
        ["answer_product_help", "no_restaurant_cards"],
        no_recommendations=True,
    ),
    _normal_seed(
        "product_nearby_reviews",
        "附近评价和大家的热帖在哪里看",
        "product_community_reviews_help",
        ["附近评价", "社区热帖", "入口帮助"],
        [],
        ["说明社区圈/帖子入口", "说明按社区或行政区查看"],
        ["硬推餐厅", "忽略社群"],
        ["answer_product_help", "open_community_hint"],
        no_recommendations=True,
    ),
    _normal_seed(
        "product_wishlist_intro",
        "心愿单和收藏是不是一个东西",
        "product_wishlist_help",
        ["心愿单", "收藏合并", "概念解释"],
        [],
        ["说明心愿单是统一收藏入口", "说明来源包括卡片/帖子/地图/Agent"],
        ["重复讲餐厅推荐"],
        ["answer_product_help", "no_restaurant_cards"],
        no_recommendations=True,
    ),
    _normal_seed(
        "product_wishlist_map",
        "心愿单里的餐厅怎么批量放到地图上",
        "product_wishlist_map_help",
        ["心愿单操作", "批量加入地图", "一键规划"],
        [],
        ["说明勾选/批量加入地图", "说明一键规划"],
        ["直接新推荐餐厅", "混入无关店"],
        ["answer_product_help", "guide_wishlist_to_map"],
        no_recommendations=True,
    ),
    _normal_seed(
        "product_wishlist_remove",
        "加入心愿单后怎么移出来",
        "product_wishlist_remove_help",
        ["移出心愿单", "取消收藏"],
        [],
        ["说明在心愿单列表或卡片按钮取消", "说明状态会同步"],
        ["推荐新店"],
        ["answer_product_help", "guide_remove_wishlist"],
        no_recommendations=True,
    ),
    _normal_seed(
        "product_fullscreen_map",
        "全屏地图页能做什么",
        "product_map_help",
        ["全屏地图", "空间选择", "路线规划"],
        [],
        ["说明定位/搜索地点", "说明餐厅点位/路线/地铁商场标注"],
        ["只给餐厅列表"],
        ["answer_product_help", "offer_map_agent_examples"],
        no_recommendations=True,
    ),
    _normal_seed(
        "product_map_agent_vs_normal",
        "普通小觅和地图小觅有什么区别",
        "product_agent_mode_help",
        ["两种agent形态", "能力区别"],
        [],
        ["说明普通对话偏需求挖掘", "说明地图小觅偏空间规划"],
        ["模糊回答", "直接推荐餐厅"],
        ["answer_product_help", "explain_agent_modes"],
        no_recommendations=True,
    ),
    _normal_seed(
        "product_detail_menu_review",
        "菜单和评价在哪里看",
        "product_detail_help",
        ["餐厅详情页", "菜单", "评价"],
        [],
        ["说明点击餐厅卡/地图点位进入详情", "说明详情页看菜单评价地址营业时间"],
        ["生成推荐卡片"],
        ["answer_product_help", "guide_detail_page"],
        no_recommendations=True,
    ),
    _normal_seed(
        "product_account_sync",
        "不登录能用吗，登录后有什么区别",
        "product_account_help",
        ["登录状态", "同步", "个人页"],
        [],
        ["说明未登录可浏览/对话", "说明登录后同步心愿单/评价/社区互动"],
        ["要求用户必须登录才能问"],
        ["answer_product_help", "explain_account_value"],
        no_recommendations=True,
    ),
    _normal_seed(
        "product_location_permission",
        "我没开定位，地图还能用吗",
        "product_location_help",
        ["未定位", "搜索地点", "定位授权"],
        [],
        ["说明可手动搜索地点", "说明定位后更准"],
        ["假装知道当前位置", "直接推荐附近餐厅"],
        ["answer_product_help", "focus_location_search"],
        no_recommendations=True,
    ),
    _normal_seed(
        "product_feedback_wrong",
        "推荐不准的时候我该怎么告诉你",
        "product_feedback_help",
        ["纠错反馈", "二次推荐规则", "记忆偏好"],
        [],
        ["说明可说太贵/太远/不吃某类/保留某家", "说明会记住并重筛"],
        ["继续重复原推荐"],
        ["answer_product_help", "guide_feedback"],
        no_recommendations=True,
    ),
    _normal_seed(
        "product_data_coverage",
        "为什么我附近有些店搜不到",
        "product_data_coverage_help",
        ["数据覆盖", "餐厅库范围", "不是即时推荐"],
        [],
        ["说明覆盖区域/数据更新时间限制", "引导用户补充店名地址"],
        ["随便推荐附近餐厅"],
        ["answer_product_help", "no_restaurant_cards"],
        no_recommendations=True,
    ),
    _normal_seed(
        "product_data_correction",
        "这家店地址错了，要怎么改",
        "product_data_correction_help",
        ["餐厅信息纠错", "地址错误"],
        [],
        ["说明可反馈店名和错误字段", "作为数据纠错信号"],
        ["继续推荐这家店"],
        ["answer_product_help", "collect_correction"],
        no_recommendations=True,
    ),
    _normal_seed(
        "product_privacy_location",
        "定位会不会保存我的位置，隐私安全吗",
        "product_privacy_help",
        ["定位权限", "隐私担忧"],
        [],
        ["说明定位用途", "说明可手动搜索地点替代"],
        ["假装知道用户位置", "直接推荐附近餐厅"],
        ["answer_product_help", "privacy_explain"],
        no_recommendations=True,
    ),
    _normal_seed(
        "product_map_blank",
        "地图空白加载不出来怎么办",
        "product_error_help",
        ["地图异常", "加载失败"],
        [],
        ["说明刷新/网络/地图服务/权限检查", "不硬推餐厅"],
        ["推荐餐厅兜底"],
        ["answer_product_help", "debug_hint"],
        no_recommendations=True,
    ),
    _normal_seed(
        "product_ai_slow",
        "为什么小觅回复很慢",
        "product_error_help",
        ["响应慢", "模型/网络", "本地规则兜底"],
        [],
        ["解释可能是模型接口或网络", "说明会走本地兜底但不乱推"],
        ["重复餐厅推荐"],
        ["answer_product_help", "latency_explain"],
        no_recommendations=True,
    ),
    _normal_seed(
        "product_review_delete",
        "评价写错了可以修改或删除吗",
        "product_review_help",
        ["评价管理", "修改/删除"],
        [],
        ["说明评价在详情/个人页承接", "说明修改删除或审核流程"],
        ["推荐餐厅"],
        ["answer_product_help", "review_management"],
        no_recommendations=True,
    ),
    _normal_seed(
        "product_report_content",
        "社区里看到不合适的评论怎么举报",
        "product_review_report_help",
        ["社区内容治理", "举报/审核"],
        [],
        ["说明举报/审核", "说明保护社区评价质量"],
        ["推荐餐厅"],
        ["answer_product_help", "report_content"],
        no_recommendations=True,
    ),
    _normal_seed(
        "product_add_restaurant",
        "我想新增一家餐厅到库里",
        "product_merchant_data_help",
        ["新增餐厅", "数据补充"],
        [],
        ["询问店名/地址/菜系/人均/标签/坐标", "说明是数据维护"],
        ["立刻推荐其他餐厅"],
        ["answer_product_help", "collect_restaurant_data"],
        no_recommendations=True,
    ),
    _normal_seed(
        "product_merchant_claim",
        "商家可以入驻或上传菜单吗",
        "product_merchant_help",
        ["商家入驻", "上传菜单"],
        [],
        ["说明当前属于数据维护/商家信息流程", "说明需要提供资料"],
        ["给用户推餐厅"],
        ["answer_product_help", "merchant_info"],
        no_recommendations=True,
    ),
    _normal_seed(
        "product_order_boundary",
        "可以直接外卖下单或付款吗",
        "product_boundary_help",
        ["产品能力边界", "外卖/支付"],
        [],
        ["说明暂不做下单支付", "说明可作为跳转或下一步提示"],
        ["假装能支付", "推荐餐厅糊弄"],
        ["answer_product_help", "boundary_explain"],
        no_recommendations=True,
    ),
    _normal_seed(
        "product_booking_boundary",
        "能帮我订座或者打电话给商家吗",
        "product_boundary_help",
        ["订座/电话边界", "人工动作"],
        [],
        ["说明可展示电话/详情但不代打电话", "给可行下一步"],
        ["承诺已订座"],
        ["answer_product_help", "boundary_explain"],
        no_recommendations=True,
    ),
    _normal_seed(
        "generic_unclear_non_food",
        "我随便问个问题你会做什么",
        "unclear_non_food_clarify",
        ["非餐饮需求不明确", "需要分流"],
        [],
        ["先说明不会硬推餐厅", "引导用户选择产品功能或吃饭推荐"],
        ["直接推荐餐厅", "兜底餐厅卡片"],
        ["ask_clarifying_question", "no_restaurant_cards"],
        no_recommendations=True,
    ),
    _normal_seed(
        "generic_product_scope",
        "这个产品除了推荐餐厅还能干嘛",
        "product_capability_help",
        ["产品能力范围", "不是餐厅推荐请求"],
        [],
        ["说明小觅、地图、社区圈、心愿单", "给出下一步问法"],
        ["只推荐餐厅"],
        ["answer_product_help", "no_restaurant_cards"],
        no_recommendations=True,
    ),
]


GENERATED_NORMAL_SEEDS: list[dict[str, Any]] = [
    _normal_seed(
        "explicit_hotpot_exact",
        "想吃火锅，人均100以内",
        "hotpot_exact_match",
        ["火锅细品类", "预算<=100", "候选必须局限在火锅"],
        ["几个人", "能否接受辣/清汤"],
        ["只推荐火锅类", "说明锅底/预算"],
        ["非火锅餐厅", "奶茶甜品", "面馆", "海鲜正餐"],
        ["render_cards", "show_category_reason"],
        expected_intents=["hotpot_exact_match"],
        required_candidate_tags_all=["火锅", "小火锅", "汤锅", "椰子鸡火锅", "潮汕牛肉火锅", "涮肉"],
    ),
    _normal_seed(
        "vague_need_clarify_first",
        "我不知道吃什么，你看着办",
        "clarify_need_first",
        ["需求模糊", "缺少口味/预算/人数/地点"],
        ["快速吃饱/清淡/甜口/聚餐/能坐"],
        ["先追问一个关键问题", "不强塞餐厅卡片"],
        ["直接推荐三家餐厅"],
        ["ask_clarifying_question", "no_restaurant_cards"],
        no_recommendations=True,
    ),
    _normal_seed(
        "sweet_not_seafood",
        "想吃甜的，不要海鲜这种正餐",
        "sweet_craving",
        ["甜口", "排除海鲜正餐", "甜品/饮品主候选"],
        ["想奶茶/蛋糕/糖水还是咖啡甜点"],
        ["明确不推海鲜", "甜品/奶茶/咖啡甜点方向"],
        ["海鲜", "刺身", "小龙虾", "日料烧肉"],
        ["render_cards", "offer_wishlist"],
        expected_intents=["sweet_craving"],
        expected_candidate_tags=["甜品", "奶茶", "咖啡", "蛋糕", "糖水", "饮品"],
        forbidden_candidate_tags=["海鲜", "刺身", "小龙虾", "日料", "烧肉"],
    ),
    _normal_seed(
        "dessert_not_sushi",
        "给我甜品，不是日料寿司烧肉",
        "sweet_craving",
        ["甜品", "明确排除日料寿司烧肉"],
        ["是否要能坐或带走"],
        ["甜品候选", "说明已排除日料正餐"],
        ["日料", "寿司", "刺身", "烧肉"],
        ["render_cards", "show_reason"],
        expected_intents=["sweet_craving"],
        expected_candidate_tags=["甜品", "蛋糕", "糖水", "奶茶", "咖啡"],
        forbidden_candidate_tags=["日料", "寿司", "刺身", "烧肉"],
    ),
    _normal_seed(
        "cool_craving_plain",
        "我想吃凉的",
        "cool_craving",
        ["凉的", "冷食/冰饮/清爽", "不是热炒热汤"],
        ["想正餐凉面/沙拉，还是冷饮冰品"],
        ["明确避开热汤热炒", "冷饮/冰品/凉面/清爽轻食方向"],
        ["炒菜", "热汤", "火锅", "冒菜", "烧烤"],
        ["render_cards", "ask_subtype_if_needed"],
        expected_intents=["cool_craving"],
        expected_candidate_tags=["凉面", "冷食", "冰品", "饮品", "奶茶", "糖水", "沙拉", "轻食", "清爽"],
        forbidden_candidate_tags=["热汤", "火锅", "冒菜", "炒菜", "烧烤", "麻辣"],
    ),
    _normal_seed(
        "cool_not_hot_meal",
        "不想吃热的，来点清爽降温的",
        "cool_craving",
        ["不热", "清爽", "降温"],
        ["是否要吃饱还是喝点冰的"],
        ["清爽冷食/冰饮", "避免热菜"],
        ["热汤", "热炒", "火锅", "砂锅"],
        ["render_cards", "show_cool_reason"],
        expected_intents=["cool_craving"],
        expected_candidate_tags=["凉面", "冷食", "冰品", "饮品", "奶茶", "糖水", "沙拉", "轻食", "清爽"],
        forbidden_candidate_tags=["热汤", "火锅", "冒菜", "炒菜", "烧烤", "麻辣"],
    ),
    _normal_seed(
        "cool_food_not_only_drink",
        "想吃冰一点的，但最好能当一餐",
        "cool_craving",
        ["冰一点", "能当一餐", "冷食优先"],
        ["能否接受凉面/沙拉/轻食"],
        ["凉面/沙拉/轻食优先", "饮品作为备选"],
        ["只推奶茶", "热炒热汤"],
        ["render_cards", "show_full_meal_option"],
        expected_intents=["cool_craving"],
        expected_candidate_tags=["凉面", "冷食", "沙拉", "轻食", "清爽"],
        forbidden_candidate_tags=["热汤", "火锅", "冒菜", "炒菜", "烧烤", "麻辣"],
    ),
    _normal_seed(
        "meta_who_are_you",
        "你是谁",
        "meta_identity",
        ["用户在问助手身份", "不是餐厅需求"],
        [],
        ["说明小觅是美食和地图选择助手", "给出可问示例"],
        ["直接推荐餐厅", "渲染餐厅卡片"],
        ["answer_capability", "no_restaurant_cards"],
        no_recommendations=True,
    ),
    _normal_seed(
        "meta_how_to_ask",
        "我该如何提问你，才能推荐更准",
        "meta_how_to_ask",
        ["用户需要提问方法", "不是即时推荐"],
        [],
        ["给提问模板", "提示位置/预算/口味/人数/后续安排"],
        ["直接推荐餐厅", "只说随便问"],
        ["answer_prompt_guide", "no_restaurant_cards"],
        no_recommendations=True,
    ),
    _normal_seed(
        "meta_capability",
        "你能帮我做什么",
        "meta_capability",
        ["能力咨询", "不是餐厅需求"],
        [],
        ["说明普通agent和地图agent能力", "给示例问题"],
        ["直接推荐餐厅"],
        ["answer_capability", "offer_agent_entry"],
        no_recommendations=True,
    ),
    _normal_seed(
        "trust_data_source",
        "这些推荐依据是什么，靠谱吗",
        "trust_explain",
        ["用户关心推荐依据", "需要解释排序维度"],
        [],
        ["说明位置/预算/口味/评分/热度/标签依据", "承认可能有误并可反馈纠偏"],
        ["空泛保证绝对准确"],
        ["explain_ranking", "offer_feedback"],
        no_recommendations=True,
    ),
    _normal_seed(
        "average_price_explain",
        "人均是什么意思，价格准吗",
        "price_explain",
        ["价格字段解释", "用户不一定要推荐"],
        [],
        ["解释人均范围", "说明会按预算过滤并提示不确定"],
        ["直接推贵店", "保证价格绝对准确"],
        ["answer_price_help", "no_restaurant_cards"],
        no_recommendations=True,
    ),
    _normal_seed(
        "budget_quality_balance",
        "便宜点但别太将就，想吃得稳",
        "budget_quality_balance",
        ["性价比", "质量稳定", "价格敏感"],
        ["预算上限"],
        ["解释性价比排序", "不只按最低价"],
        ["只推最低价", "推荐明显高价"],
        ["render_cards", "show_value_reason"],
        known_preferences=["price_sensitive"],
    ),
    _normal_seed(
        "office_worker_quick",
        "我是上班族，中午只有40分钟，别太有味道",
        "office_quick_meal",
        ["上班族", "午休时间短", "低气味", "快速"],
        ["预算", "是否需要可外带"],
        ["出餐速度", "低气味", "离办公点近"],
        ["火锅烧烤", "重油烟"],
        ["render_cards", "show_time_plan"],
        location="陆家嘴",
    ),
    _normal_seed(
        "tourist_local_light",
        "游客来上海，想吃本地特色但别太重口",
        "tourist_local_food",
        ["游客", "上海特色", "不重口"],
        ["预算", "所在区域"],
        ["本地特色", "口味稳妥", "交通友好"],
        ["重辣", "全国连锁无特色"],
        ["render_cards", "offer_map"],
        location="黄浦区",
    ),
    _normal_seed(
        "elderly_low_salt",
        "带老人吃，少盐少油，走路少一点",
        "elderly_light_accessible",
        ["老人", "少盐少油", "少走路"],
        ["是否需要电梯/包间"],
        ["清淡", "动线便利", "座位舒适"],
        ["重口味", "楼梯多", "拥挤小店"],
        ["render_cards", "offer_map"],
        known_preferences=["prefer_light", "distance_sensitive"],
    ),
    _normal_seed(
        "no_pork_preference",
        "不吃猪肉，想吃点能吃饱的",
        "avoid_pork_full_meal",
        ["不吃猪肉", "饱腹"],
        ["是否牛羊鸡蛋奶都可以"],
        ["避开猪肉主打", "给饱腹选择"],
        ["猪肉", "叉烧", "大肠面", "排骨"],
        ["render_cards", "persist_avoidance"],
    ),
    _normal_seed(
        "pregnant_avoid_raw",
        "孕妇一起吃，别生冷，口味清淡点",
        "pregnancy_safe_meal",
        ["孕妇同行", "避免生冷", "清淡"],
        ["是否有其他忌口"],
        ["熟食", "清淡", "安全提醒"],
        ["刺身", "生食", "重辣"],
        ["render_cards", "show_safety_notes"],
        known_preferences=["prefer_light"],
        forbidden_candidate_tags=["刺身", "生食", "麻辣", "川菜", "湘菜", "烧烤", "小龙虾"],
    ),
    _normal_seed(
        "social_anxiety_quiet",
        "我不想去人很多的店，想安静点吃",
        "quiet_low_crowd",
        ["低人流", "安静", "心理舒适"],
        ["预算", "一个人还是多人"],
        ["安静理由", "避开排队和网红店"],
        ["网红排队", "热闹大排档"],
        ["render_cards", "show_crowd_risk"],
    ),
    _normal_seed(
        "split_bill_group",
        "5个人聚餐，希望好AA，人均80以内",
        "group_split_bill",
        ["5人", "AA友好", "人均<=80"],
        ["是否有人忌口"],
        ["多人点菜", "价格可控", "分摊友好"],
        ["单人快餐", "高客单"],
        ["render_cards", "offer_groupbuy"],
    ),
    _normal_seed(
        "deal_priority",
        "有团购优惠的优先，但不要太远",
        "deal_distance_balance",
        ["团购优惠", "距离敏感"],
        ["预算/口味"],
        ["优惠", "距离", "到店风险"],
        ["只看折扣忽略距离"],
        ["render_cards", "show_deal_badges"],
        known_preferences=["distance_sensitive"],
    ),
    _normal_seed(
        "weather_hot_cold_drink",
        "太热了，想喝点冰的但不要太甜",
        "cold_drink_less_sugar",
        ["天气热", "冰饮", "少糖"],
        ["是否要奶茶/咖啡/果茶"],
        ["冰饮", "少糖建议", "可带走"],
        ["正餐主菜", "默认全糖"],
        ["render_cards", "show_sugar_notes"],
        expected_intents=["sweet_craving", "less_sugar"],
        expected_candidate_tags=["奶茶", "饮品", "咖啡", "冰品"],
        forbidden_candidate_tags=["海鲜", "日料", "火锅", "烧烤"],
    ),
    _normal_seed(
        "conflict_hotpot_no_spicy",
        "想吃火锅但不要辣，也别太贵",
        "resolve_conflict",
        ["火锅欲望", "不辣", "价格敏感"],
        ["能否接受椰子鸡/番茄锅/小火锅"],
        ["折中方案", "不辣锅底", "预算说明"],
        ["默认麻辣锅", "贵价火锅"],
        ["ask_clarifying_question", "render_compromise_cards"],
        known_preferences=["avoid_spicy", "price_sensitive"],
    ),
]


GENERATED_MAP_SEEDS: list[dict[str, Any]] = [
    _map_seed("map_subway_line", "吃完要坐2号线，找离站近又不绕的", "route_to_subway", ["2号线", "离站近", "少绕路"], ["具体方向/站点"], ["标地铁", "比较到站距离"], ["只看评分"], ["mark_subway_stations", "rank_by_route"], ["show_plan_cards"], [31.2304, 121.4737], "静安区"),
    _map_seed("map_mall_kids", "带小孩，吃完想去商场玩，厕所方便点", "kid_mall_route", ["带娃", "商场游乐", "厕所便利"], ["孩子年龄/预算"], ["亲子餐厅", "商场标注"], ["重辣小店"], ["mark_malls", "mark_kid_friendly_restaurants"], ["show_family_plan"], [31.1128, 121.3817], "闵行区"),
    _map_seed("map_exhibition_timing", "展会一小时后开始，找路上能快速吃的", "event_route", ["展会", "一小时", "沿路快速"], ["展会地点/入口"], ["沿路餐厅", "时间风险"], ["反方向慢餐"], ["mark_event", "mark_route_food"], ["ask_time"], [31.2204, 121.4246], "长宁区"),
    _map_seed("map_night_safety", "晚上一个人，想吃完安全回酒店", "hotel_nearby_safe_route", ["夜间", "一人", "回酒店安全"], ["酒店位置/交通方式"], ["安全路线", "近距离"], ["偏僻路线"], ["mark_hotel_if_known", "rank_by_night_safety"], ["ask_location_if_needed"], [31.2215, 121.5440], "浦东新区"),
    _map_seed("map_accessibility", "朋友坐轮椅，找无障碍好走的餐厅", "accessible_route", ["轮椅", "无障碍", "少台阶"], ["是否需要电梯/停车"], ["无障碍动线", "入口便利"], ["楼梯多小店"], ["rank_by_accessibility", "mark_dropoff_points"], ["show_accessibility_notes"], [31.1935, 121.4367], "徐汇区"),
    _map_seed("map_parking_then_food", "开车过去，停车方便比评分更重要", "parking_priority", ["开车", "停车优先", "评分次要"], ["预计到达时间"], ["停车点", "步行到店距离"], ["只按评分"], ["mark_parking_or_mall", "rank_by_parking"], ["show_map_annotations"], [31.2494, 121.3976], "普陀区"),
    _map_seed("map_home_direction", "吃完往杨浦方向回家，别让我反方向", "home_commute_after_meal", ["回家方向", "杨浦", "避免反方向"], ["交通方式/具体方向"], ["顺路餐厅", "回程便利"], ["反方向推荐"], ["rank_by_exit_convenience", "draw_sequence"], ["ask_destination"], [31.2304, 121.4737], "黄浦区"),
    _map_seed("map_rain_shelter", "下雨，尽量商场里解决，少走露天", "rain_sheltered_route", ["雨天", "商场内", "少露天"], ["是否接受连锁"], ["商场/连廊", "遮蔽路线"], ["露天长距离"], ["mark_malls", "rank_by_shelter"], ["show_weather_sensitive_plan"], [31.2290, 121.4598], "静安区"),
    _map_seed("map_compare_price_distance", "这几家帮我按价格和距离综合排一下", "compare_candidates_spatial", ["价格", "距离", "综合排序"], ["是否有口味优先级"], ["排序理由", "保留候选"], ["重新随机换店"], ["highlight_candidates", "rerank_points"], ["show_comparison_card"], [31.2914, 121.5070], "杨浦区", ["地图上已有三家候选"]),
    _map_seed("map_wishlist_batch", "心愿单里选中的几家放地图上，我看路线", "wishlist_to_map", ["心愿单", "批量加入地图", "路线比较"], ["按距离/价格/下一站排序"], ["只展示心愿单点位", "路线比较"], ["混入无关新店"], ["clear_old_points", "add_wishlist_points", "fit_bounds"], ["open_wishlist_panel"], [31.2646, 121.5051], "虹口区"),
    _map_seed("map_agent_help", "地图页我该怎么问你", "map_help", ["地图agent用法", "不是即时推荐"], [], ["说明可问位置/下一站/交通/预算/心愿单"], ["直接推荐餐厅"], ["hold_current_points"], ["answer_prompt_guide"], [31.2304, 121.4737], "静安区", no_recommendations=True),
    _map_seed("map_no_location_help", "我没开定位，可以先做什么", "need_location", ["未定位", "需要搜索或授权"], ["定位或搜索地点"], ["说明先定位/搜索", "可先按区域粗筛"], ["假装知道位置"], ["request_location_or_search"], ["focus_location_search"], None, None, no_recommendations=True),
]


CUISINE_AGENT_SEEDS: list[dict[str, Any]] = [
    _normal_seed("korean_craving", "想吃韩餐，最好有部队锅或者拌饭", "korean_craving", ["韩餐", "部队锅/拌饭"], ["预算", "能否接受烤肉"], ["按韩餐筛选", "说明菜品匹配"], ["火锅/西餐/小面混推"], ["render_cards"], expected_candidate_tags=["韩餐", "韩国料理", "部队锅", "石锅拌饭", "韩式"], forbidden_candidate_tags=["火锅", "西餐", "小面", "川菜"]),
    _normal_seed("thai_craving", "想吃泰餐，酸辣开胃一点", "thai_craving", ["泰餐", "酸辣开胃"], ["预算", "是否能吃辣"], ["按泰餐筛选", "冬阴功/咖喱方向"], ["韩餐/中餐泛推"], ["render_cards"], expected_candidate_tags=["泰餐", "泰国菜", "冬阴功", "咖喱", "泰式"], forbidden_candidate_tags=["韩餐", "东北菜", "小面", "日料"]),
    _normal_seed("xinjiang_craving", "想吃新疆菜，大盘鸡或者手抓饭", "xinjiang_craving", ["新疆菜", "大盘鸡/手抓饭"], ["几个人", "预算"], ["按新疆菜筛选", "分量说明"], ["西餐/甜品混推"], ["render_cards"], expected_candidate_tags=["新疆菜", "大盘鸡", "手抓饭", "烤包子", "羊肉串"], forbidden_candidate_tags=["西餐", "甜品", "日料", "小面"]),
    _normal_seed("northeast_craving", "想吃东北菜，量大一点", "northeast_craving", ["东北菜", "量大"], ["几个人", "是否想铁锅炖"], ["按东北菜筛选", "分量/聚餐理由"], ["海鲜/日料/甜品混推"], ["render_cards"], expected_candidate_tags=["东北菜", "锅包肉", "铁锅炖", "饺子", "量大"], forbidden_candidate_tags=["海鲜", "日料", "甜品", "奶茶"]),
    _normal_seed("shanghai_local_craving", "想吃上海本帮菜，带朋友尝尝本地特色", "shanghai_craving", ["本帮菜", "上海本地特色"], ["预算", "是否长辈同行"], ["按本帮/上海菜筛选", "本地特色理由"], ["川湘辣菜混推"], ["render_cards"], expected_candidate_tags=["本帮菜", "上海菜", "本地菜", "红烧肉", "生煎", "小笼"], forbidden_candidate_tags=["川菜", "湘菜", "麻辣", "火锅"]),
    _normal_seed("cantonese_teahouse_craving", "想吃粤菜或茶餐厅，云吞面烧腊都可以", "cantonese_craving", ["粤菜/茶餐厅", "云吞面/烧腊"], ["预算", "堂食还是快吃"], ["按港式/粤菜筛选", "云吞面/烧腊方向"], ["西餐/甜品混推"], ["render_cards"], expected_candidate_tags=["粤菜", "港式", "茶餐厅", "云吞面", "烧腊", "早茶"], forbidden_candidate_tags=["西餐", "甜品", "火锅", "日料"]),
    _normal_seed("barbecue_craving", "想吃烧烤烤串，朋友一起", "barbecue_craving", ["烧烤/烤串", "朋友聚餐"], ["预算", "是否能等位"], ["按烧烤/烤肉筛选", "适合多人理由"], ["奶茶/轻食混推"], ["render_cards"], expected_candidate_tags=["烧烤", "烤串", "烤肉", "羊肉串", "夜宵"], forbidden_candidate_tags=["奶茶", "轻食", "甜品", "咖啡"]),
    _normal_seed("noodle_craving", "想吃粉面，米线或者汤面都行", "noodles_craving", ["粉面", "米线/汤面"], ["清淡还是重口", "预算"], ["按粉面筛选", "出餐速度说明"], ["咖啡/西餐/甜品混推"], ["render_cards"], expected_candidate_tags=["面馆", "面", "粉", "米线", "汤面", "拌面"], forbidden_candidate_tags=["咖啡", "西餐", "甜品", "海鲜"]),
    _normal_seed("coffee_plain_craving", "我想喝咖啡", "coffee_craving", ["咖啡", "非正餐"], ["是否要办公/安静/可外带"], ["按咖啡店筛选", "不推正餐"], ["本帮菜/烧烤/海鲜/小面混推"], ["render_cards"], expected_candidate_tags=["咖啡", "咖啡馆", "办公", "插座", "安静"], forbidden_candidate_tags=["本帮菜", "上海菜", "烧烤", "海鲜", "小面", "川菜", "湘菜", "火锅"]),
    _normal_seed("cafe_work_craving", "想找咖啡店办公，有插座安静一点", "cafe_work", ["咖啡", "办公", "插座", "安静"], ["坐多久", "是否要轻食"], ["按咖啡办公筛选", "插座/安静理由"], ["正餐大店混推"], ["render_cards"], expected_candidate_tags=["咖啡", "办公", "自习", "插座", "安静"], forbidden_candidate_tags=["火锅", "烧烤", "海鲜", "大排档"]),
    _normal_seed("seafood_craving", "想吃海鲜，小龙虾或者生蚝都可以", "seafood_craving", ["海鲜", "小龙虾/生蚝"], ["预算", "是否能接受刺身"], ["按海鲜筛选", "鲜味/聚餐理由"], ["小面/甜品/西餐混推"], ["render_cards"], expected_candidate_tags=["海鲜", "小龙虾", "生蚝", "虾", "蟹"], forbidden_candidate_tags=["小面", "甜品", "西餐", "奶茶"]),
    _normal_seed("tea_drink_craving", "想喝奶茶果茶，别推正餐", "tea_drink_craving", ["茶饮/奶茶", "非正餐"], ["少糖/冰度", "是否要可坐"], ["按茶饮筛选", "不推正餐"], ["火锅/海鲜/东北菜"], ["render_cards"], expected_candidate_tags=["奶茶", "饮品", "果茶", "茶饮", "冷饮"], forbidden_candidate_tags=["火锅", "海鲜", "东北菜", "小面"]),
]


def _variant_user_text(seed_user: str, variant_template: str, scenario_template: str) -> str:
    phrased = variant_template.format(user=seed_user)
    return scenario_template.format(text=phrased)


def _scenario_variants_for(seed: dict[str, Any], mode: str) -> list[dict[str, Any]]:
    if mode == "map_agent":
        return MAP_SCENARIO_VARIANTS
    if seed.get("expected", {}).get("no_recommendations"):
        return PRODUCT_SCENARIO_VARIANTS
    return NORMAL_SCENARIO_VARIANTS


def _merge_unique_list(target: dict[str, Any], key: str, values: list[str]) -> None:
    if not values:
        return
    current = list(target.get(key, []))
    for value in values:
        if value not in current:
            current.append(value)
    target[key] = current


def _build_case(seed: dict[str, Any], mode: str, seed_index: int, variant_index: int, scenario_index: int) -> dict[str, Any]:
    variant_name, variant_template = PHRASING_VARIANTS[variant_index]
    scenario = _scenario_variants_for(seed, mode)[scenario_index]
    expected = deepcopy(seed["expected"])
    _merge_unique_list(expected, "must_infer", scenario.get("must_infer", []))
    _merge_unique_list(expected, "must_include", scenario.get("must_include", []))
    if mode == "map_agent":
        _merge_unique_list(expected, "map_actions", scenario.get("map_actions", []))

    context = deepcopy(seed.get("context", {}))
    if scenario.get("known_preferences"):
        known = list(context.get("known_preferences", []))
        for value in scenario["known_preferences"]:
            if value not in known:
                known.append(value)
        context["known_preferences"] = known

    case = {
        "id": f"{mode}-{seed_index + 1:03d}-{variant_index + 1:02d}-{scenario_index + 1}",
        "mode": mode,
        "category": seed["category"],
        "variant": variant_name,
        "scenario_variant": scenario["name"],
        "turns": [],
        "context": context,
        "expected": expected,
        "evaluation_checks": [
            "must_respect_user_preferences",
            "must_not_hallucinate_restaurant_names",
            "recommendation_text_must_match_structured_cards",
            "ask_at_most_one_key_clarifying_question_when_needed",
        ],
    }
    for item in seed.get("history", []):
        case["turns"].append({"role": "user", "content": item})
    case["turns"].append({
        "role": "user",
        "content": _variant_user_text(seed["user"], variant_template, scenario["template"]),
    })
    if mode == "map_agent":
        case["evaluation_checks"].extend([
            "map_actions_must_be_explicit",
            "old_points_should_be_cleared_when_user_requests_recommendation_replacement",
            "spatial_reasoning_should_include_next_destination_when_known",
        ])
    else:
        case["evaluation_checks"].extend([
            "normal_agent_should_focus_on_need_discovery",
            "card_actions_should_include_wishlist_or_map_handoff_when_relevant",
        ])
    return case


def build_training_cases() -> list[dict[str, Any]]:
    cases: list[dict[str, Any]] = []
    normal_seeds = (
        NORMAL_AGENT_SEEDS[:12]
        + CUISINE_AGENT_SEEDS
        + NORMAL_AGENT_SEEDS[12:31]
        + PRODUCT_AGENT_SEEDS[:8]
    )[:50]
    map_seeds = (MAP_AGENT_SEEDS + GENERATED_MAP_SEEDS)[:50]
    for seed_index, seed in enumerate(normal_seeds):
        for variant_index in range(len(PHRASING_VARIANTS)):
            for scenario_index in range(len(_scenario_variants_for(seed, "normal_agent"))):
                cases.append(_build_case(seed, "normal_agent", seed_index, variant_index, scenario_index))
    for seed_index, seed in enumerate(map_seeds):
        for variant_index in range(len(PHRASING_VARIANTS)):
            for scenario_index in range(len(_scenario_variants_for(seed, "map_agent"))):
                cases.append(_build_case(seed, "map_agent", seed_index, variant_index, scenario_index))
    if len(cases) != 5000:
        raise RuntimeError(f"Expected 5000 cases, got {len(cases)}")
    return cases


TRAINING_CASES = build_training_cases()


if __name__ == "__main__":
    print(json.dumps(TRAINING_CASES, ensure_ascii=False, indent=2))
